language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies

if: type != push 

script: npm run build # Here you could also run the build step of your application
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: npm run deploy:staging
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  # deploy master to production
  - provider: script
    script: npm run deploy:prod
    skip_cleanup: true
    on:
      master: true

after_deploy:
  - if [ "$TRAVIS_BRANCH" = "development" ]; then npm run alias:dev;
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run alias:prod; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run release; fi
  - npm run cleanup
      
